### ISSUE TITLE
Sections screenshot differences

### ISSUE THREAD

**Issue by HannahDelaney** [HannahDelaney/sections#1]
I have three of the five screenshots within the parameters markbot is requesting, but two are outside (23% and 18% difference). I am not sure how to change the margins/paddings to fix this without altering the other screenshot values. I could use some pointers!

@thomasjbradley

**Comment by thomasjbradley** [comment]
The biggest problem is the size of the image—it’s too big. I think it could be related to padding. The `.image` & `.text` should have `padding` on them instead of `margin`. And I think that might help.

**Comment by HannahDelaney** [comment]
Thanks very much, that basically solved it! My 960px screenshot is still at 16%, but maybe I can find a way to fix that.

**Comment by HannahDelaney** [comment]
Never mind, I adjusted the padding until it worked. All good!
